### PR TITLE
Added support for .dk domains

### PR DESCRIPTION
**Pull request by TorbenLundsgaard**

### CODE REVIEW

**Comment by jsmitty12** [comment]
Thanks for the PR--this is going to be a great addition to phpWhoIs!

I have two requests:
1. One of my long-term goals for the project is to update the code to follow the [PSR-12](https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md) coding style. Will you update the `whois.dk.php` file to follow PSR-12? (I think simply adding braces to the `if` statements on lines 25 and 45, and then moving the braces from the ends of lines 30 and 32 to the next lines will do it.)
2. Another long-term goal is to create PHPUnit tests for the system (leveraging fixtures to ensure that the tests are always fast). Will you add one or more tests for .dk domains following the pattern started in the `/tests` directory?

Please let me know if you have any questions, and thanks again for your contribution!

**Comment by TorbenLundsgaard** [comment]
I have fixed the code style and will write a test

**Comment by TorbenLundsgaard** [comment]
@jsmitty12 I have no idea why the test i failing. Can you help?

**Comment by jsmitty12** [comment]
Yep... I'm looking at it now

**Comment by jsmitty12** [comment]
I don't know what error you're getting, but initially I got `Error : Class 'dk_handler' not found`. To fix that, simply run `composer dump-autoload`.

Does that happen to be the error you are getting?

**Comment by TorbenLundsgaard** [comment]
@jsmitty12 I fixed the problem and Travis is happy. However, there is a problem with Scrutinizer but it doesn't seem to be related to my code.

**Pull request merged**
